db:
  host: '34.93.168.202'
  port: '3306'
  username: 'root'
  password: 'Mulesoft@feb24'
  database: 'main'
sf:
  email: 'soniyaarockiya@gmail.com'
  password: 'Soniya@321'
  token: 'HaTEyJLEDEY7gu4cfhYw1VLHB'